version: "3.7"
services:
  rags_app:
    build:
      context: .
    container_name: rags_app
    command: ["/start-reload.sh"]
    env_file:
      - ../rags.env
    environment:
      - RAGS_DATA_DIR=/rags/data
    volumes:
      - ./rags_app:/rags/rags_app
      - ../logs:/rags/logs
      - ../rags_projects:/rags/projects
      - "${RAGS_APP_DATA_DIR}:/rags/data"
    ports:
      - "${RAGS_APP_PORT}:${RAGS_APP_PORT}"

  rags_graph:
    build:
      context: ./rags_graph/
    container_name: rags_graph
    entrypoint:
      - /bin/sh
      - -c
      - "chown neo4j:neo4j /ssl && /docker-entrypoint.sh neo4j"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk/jre
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_connectors_default__listen__address=0.0.0.0
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*  # un-sandbox apoc procedures: http://blog.armbruster-it.de/2017/05/running-neo4j-3-2-apoc-docker/
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MEMORY}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_MEMORY}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_CACHE_MEMORY}
      - NEO4J_dbms_read__only=${NEO4J_READONLY}
      - NEO4J_dbms_jvm_additional=-XX:+UnlockExperimentalVMOptions -XX:+UseZGC
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
      - "${NEO4J_HTTPS_PORT}:${NEO4J_HTTPS_PORT}"
    volumes:
      - ../neo4j_data:/data
      - ../neo4j_logs:/logs
      - ../neo4j_ssl:/ssl
