version: "3.7"
services:
  rags_app:
    build:
      context: .
    container_name: rags_app
    command: ["/start-reload.sh"]
    env_file:
      - ../rags.env
    environment:
      - RAGS_DATA_DIR=/rags/data
    volumes:
      - ./rags_app:/rags/rags_app
      - ../logs:/rags/logs
      - ../rags_projects:/rags/projects
      - "${RAGS_APP_DATA_DIR}:/rags/data"
    ports:
      - "${RAGS_APP_PORT}:${RAGS_APP_PORT}"
    networks:
      - rags_network

  rags_graph:
    build:
      context: ./rags_graph/
    container_name: rags_graph
    entrypoint:
      - /bin/sh
      - -c
      - "chown neo4j:neo4j /ssl && /docker-entrypoint.sh neo4j"
    environment:
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MEMORY}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_MEMORY}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_CACHE_MEMORY}
      - NEO4J_dbms_security_auth__enabled=False
    volumes:
      - ../neo4j_data:/data
      - ../neo4j_logs:/logs
      - ../neo4j_ssl:/ssl
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
      - "${NEO4J_HTTPS_PORT}:${NEO4J_HTTPS_PORT}"
    networks:
      - rags_network

networks:
  rags_network:
    name: rags_network